language: node_js

node_js:
  - node

services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

env:
  - NODE_ENV=test

after_success:
  - npm run coverage
  - codeclimate-test-reporter < coverage/lcov.info
