language: node_js

node_js:
  - node

services:
  - postgresql

before_script:
  - npm install -g codeclimate-test-reporter
  - psql -c 'drop database if exists hellobooks;' -U postgres
  - psql -c 'create database hellobooks;' -U postgres
  - psql -c "create user andeladeveloper with login password 'oracle';" -U postgres

env:
  - NODE_ENV=test

after_success:
  - npm run coverage
  - codeclimate-test-reporter < coverage/lcov.info
