export const SET_AUTH_USERS = 'SET_AUTH_USERS';
export const LOG_OUT_USERS = 'LOG_OUT_USERS';
export const SET_AUTH_USERS_ERROR = 'SET_AUTH_USERS_ERROR';
export const GET_ALL_BOOKS = 'GET_ALL_BOOKS';
export const GET_ALL_BOOKS_ERROR = 'GET_ALL_BOOKS_ERROR';
export const BORROW_A_BOOK = 'BORROW_A_BOOK';
export const BORROW_A_BOOK_ERROR = 'BORROW_A_BOOK_ERROR';
export const GET_USER_HISTORY = 'GET_USER_HISTORY';
export const GET_USER_HISTORY_ERROR = 'GET_USER_HISTORY_ERROR';
export const RETURN_A_BOOK = 'RETURN_A_BOOK';
export const RETURN_A_BOOK_ERROR = 'RETURN_A_BOOK_ERROR';
export const ADD_BOOK = 'ADD_BOOK';
export const ADD_BOOK_ERROR = 'ADD_BOOK_ERROR';
export const DELETE_BOOK = 'DELETE_BOOK';
export const DELETE_BOOK_ERROR = 'DELETE_BOOK_ERROR';
export const GET_BOOK_CATEGORY = 'GET_BOOK_CATEGORY';
export const GET_BOOK_CATEGORY_ERROR = 'GET_BOOK_CATEGORY_ERROR';
export const CREATE_BOOK_CATEGORY = 'CREATE_BOOK_CATEGORY';
export const CREATE_BOOK_CATEGORY_ERROR = 'CREATE_BOOK_CATEGORY_ERROR';
export const EDIT_BOOK = 'EDIT_BOOK';
export const EDIT_BOOK_ERROR = 'EDIT_BOOK_ERROR';
export const GET_ALL_BOOKS_BY_CATEGORY = 'GET_ALL_BOOKS_BY_CATEGORY';
export const GET_ALL_BOOKS_BY_CATEGORY_ERROR =
 'GET_ALL_BOOKS_BY_CATEGORY_ERROR';
export const CHANGE_USERS_PASSWORD = 'CHANGE_USERS_PASSWORD';
export const CHANGE_USERS_PASSWORD_ERROR = 'CHANGE_USERS_PASSWORD_ERROR';
export const GET_ALL_NOTIFICATIONS = 'GET_ALL_NOTIFICATIONS';
export const GET_ALL_NOTIFICATIONS_ERROR = 'GET_ALL_NOTIFICATIONS_ERROR';


