export const SET_AUTH_USERS = 'SET_AUTH_USERS';
export const SET_AUTH_USERS_ERROR = 'SET_AUTH_USERS_ERROR';
export const GET_ALL_BOOKS = 'GET_ALL_BOOKS';
export const GET_ALL_BOOKS_ERROR = 'GET_ALL_BOOKS_ERROR';
export const BORROW_A_BOOK = 'BORROW_A_BOOK';
export const BORROW_A_BOOK_ERROR = 'BORROW_A_BOOK_ERROR';
export const GET_USER_HISTORY = 'GET_USER_HISTORY';
export const GET_USER_HISTORY_ERROR = 'GET_USER_HISTORY_ERROR';
